# Server
server.port=8080

# Database (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-proud-snow-apn2xrit-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_aVTmoDqg4cQ6
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Mail (Gmail SMTP for demo)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=abishekappu15@gmail.com
spring.mail.password=zcoqykzqburfodim
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# File Upload Location (Local)
app.file.upload-dir=uploads/
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
